baseurl = "http://shiatsu-shi.fr"
title = "Dimension"
theme = "dimension"
publishDir = "docs"
languageCode = "fr-FR"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  title = "Dimension"
  description = 'SUIVRE SON CHEMIN AVEC LE SHIATSU'
  logo = "fa-sign-language"
  copyright = "shiatsu-shi.fr"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"

[languages]
[languages.en]
languageName = ""
weight = 1
title = "faire une pause"
description = 'suivre son chemin avec le shiatsu'

[languages.fr]
languageName = ""
weight = 2
title = ""
description = ''
